# Generated by Django 4.0.1 on 2022-01-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='products',
            new_name='product',
        ),
    ]
